on: [push]

jobs:
  my_first_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job automatically trigerred by a ${{ github.event.name }} event."
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run script from repo
        run: |
          ls
          pwd
          sh ./test.sh
        shell: bash

